version: '3'
services:

  config:
    hostname: config
    image: springfivebyexample/config
    ports:
      - "5000:5000"
    networks:
      - airline

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.7.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - airline

  mysql:
    hostname: mysql
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zipkin
    networks:
      - airline

  redis:
    hostname: redis
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    networks:
      - airline

  zipkin:
    hostname: zipkin
    restart: always
    image: springfivebyexample/zipkin
    ports:
      - "9999:9999"
    networks:
      - airline

  discovery:
    hostname: discovery
    restart: always
    image: springfivebyexample/discovery
    ports:
      - "8761:8761"
    networks:
      - airline

  edge:
    hostname: edge
    restart: always
    image: springfivebyexample/edge
    ports:
      - "8888:8888"
    networks:
      - airline

  hystrix_dashboard:
    hostname: hystrix_dashboard
    restart: always
    image: springfivebyexample/hystrix_dashboard
    ports:
      - "50010:50010"
    networks:
      - airline

  turbine:
    hostname: turbine
    restart: always
    image: springfivebyexample/turbine
    ports:
      - "8010:8010"
      - "8080:8080"
    networks:
      - airline

  mail:
    hostname: mail
    restart: always
    image: springfivebyexample/mail
    ports:
      - "50050:50050"
    networks:
      - airline

  admin:
    hostname: admin
    restart: always
    image: springfivebyexample/admin
    ports:
      - "50015:50015"
    networks:
      - airline

  mongo:
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - airline

networks:
  airline:
    driver: bridge