server:
  port: 50015
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
  data:
    mongodb:
      database: bookings
      host: mongo
  oauth2:
    resource:
      userInfoUri: http://auth:7777/credential

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

planes:
  service: PLANES
  oauth:
    client_id: 442cf4015509eda9c03e5ca3aceef752
    client_secret: 4f7ec648a48b9d3fa239b497f7b6b4d8019697bd

fares:
  service: FARES
  oauth:
    client_id: 47d35bda81f57a8eb8f85a410e18001b
    client_secret: e186b815cfc1a9988030a21ad8f32d8a6559f3b8

flights:
  service: FLIGHTS
  oauth:
    client_id: 917092f2d185310c0f4fa8ba3296e33d
    client_secret: f7641c289245d5d43d0aa96d0c14dbc6afba31fc

auth:
  service: AUTH
  path: /oauth/token

amqp:
  payments:
    queue:
      request: request_payment_queue
      response: response_payment_queue
    exchange:
      payment: payments
    key:
      request: request_payment
      response: response_payment
  mail:
    exchange:
      mail: mails
    queue:
      request: send-mail-request

config:
  oauth2:
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIICXQIBAAKBgQDNQZKqTlO/+2b4ZdhqGJzGBDltb5PZmBz1ALN2YLvt341pH6i5
      mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE/myh1zM6m8cbL5cYFPyP099t
      hbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26hL9dSAZuA8xExjlPmQIDAQAB
      AoGAImnYGU3ApPOVtBf/TOqLfne+2SZX96eVU06myDY3zA4rO3DfbR7CzCLE6qPn
      yDAIiW0UQBs0oBDdWOnOqz5YaePZu/yrLyj6KM6Q2e9ywRDtDh3ywrSfGpjdSvvo
      aeL1WesBWsgWv1vFKKvES7ILFLUxKwyCRC2Lgh7aI9GGZfECQQD84m98Yrehhin3
      fZuRaBNIu348Ci7ZFZmrvyxAIxrV4jBjpACW0RM2BvF5oYM2gOJqIfBOVjmPwUro
      bYEFcHRvAkEAz8jsfmxsZVwh3Y/Y47BzhKIC5FLaads541jNjVWfrPirljyCy1n4
      sg3WQH2IEyap3WTP84+csCtsfNfyK7fQdwJBAJNRyobY74cupJYkW5OK4OkXKQQL
      Hp2iosJV/Y5jpQeC3JO/gARcSmfIBbbI66q9zKjtmpPYUXI4tc3PtUEY8QsCQQCc
      xySyC0sKe6bNzyC+Q8AVvkxiTKWiI5idEr8duhJd589H72Zc2wkMB+a2CEGo+Y5H
      jy5cvuph/pG/7Qw7sljnAkAy/feClt1mUEiAcWrHRwcQ71AoA0+21yC9VkqPNrn3
      w7OEg8gBqPjRlXBNb00QieNeGGSkXOoU6gFschR22Dzy
      -----END RSA PRIVATE KEY-----
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
      b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
      /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
      hL9dSAZuA8xExjlPmQIDAQAB
      -----END PUBLIC KEY-----